package com.jslee1972.vlinkerobd.ui

/**
 * Traditional-Chinese display names for live PID fields (车速/rpm excluded — those already have
 * dedicated Chinese labels on the gauges). Only English and Traditional Chinese are supported
 * today; an untranslated field falls back to its raw camelCase key rather than a fabricated name,
 * same honesty rule [com.jslee1972.vlinkerobd.obd.DtcDescriptions] uses for fault codes.
 */
object PidDisplayNames {
    private val zh: Map<String, String> = mapOf(
        // universal-obd2.json
        "coolantTempC" to "水溫",
        "engineLoadPercent" to "引擎負載",
        "throttlePercent" to "節氣門開度",
        "controlModuleVoltage" to "電瓶電壓",
        "intakeAirTempC" to "進氣溫度",
        "mafGramsPerSec" to "進氣流量",
        "intakeManifoldPressureKPA" to "進氣歧管壓力",
        "fuelPressureKPA" to "燃油壓力",
        "barometricPressureKPA" to "大氣壓力",
        "fuelLevelPercent" to "油量",
        "ambientAirTempC" to "外部氣溫",
        "engineOilTempC" to "機油溫度",
        "runtimeSinceStartSec" to "啟動後運轉時間",
        "shortTermFuelTrimBank1Percent" to "短期燃油修正（Bank 1）",
        "longTermFuelTrimBank1Percent" to "長期燃油修正（Bank 1）",
        "shortTermFuelTrimBank2Percent" to "短期燃油修正（Bank 2）",
        "longTermFuelTrimBank2Percent" to "長期燃油修正（Bank 2）",
        "timingAdvanceDegrees" to "點火提前角",
        "distanceWithMilOnKM" to "故障燈亮起後行駛里程",
        "chargeAirCoolerTempC" to "中冷器溫度",
        "lambdaBank1Sensor1" to "氧感應器 Lambda",
        "boostPressureCommandedKPA" to "增壓目標值",
        "boostPressureActualKPA" to "增壓實際值",
        "exhaustPressureBank1KPA" to "排氣壓力",
        "dpfInletPressureKPA" to "DPF 進氣壓力",
        "dpfOutletPressureKPA" to "DPF 出氣壓力",
        "fuelRailPressureCommandedKPA" to "燃油軌壓目標值",
        "fuelRailPressureActualKPA" to "燃油軌壓實際值",
        "engineFuelRateLPH" to "油耗率",
        "exhaustGasTempBank1Sensor1C" to "排氣溫度（感應器 1）",
        "exhaustGasTempBank1Sensor2C" to "排氣溫度（感應器 2）",
        "exhaustGasTempBank1Sensor3C" to "排氣溫度（感應器 3）",
        "noxBank1Sensor1PPM" to "氮氧化物濃度",
        "absoluteLoadPercent" to "絕對引擎負載",
        "commandedEquivalenceRatio" to "指令當量比",
        "relativeThrottlePercent" to "相對節氣門開度",
        "ethanolFuelPercent" to "乙醇燃料比例",
        "fuelRailPressureAbsoluteKPA" to "燃油軌絕對壓力",
        "relativeAcceleratorPedalPercent" to "相對油門踏板位置",
        "driverDemandTorquePercent" to "駕駛需求扭矩",
        "actualEngineTorquePercent" to "實際引擎扭矩",
        "engineReferenceTorqueNM" to "引擎參考扭矩",
        // citroen.json (PSA)
        "turboPressureBar" to "渦輪增壓壓力",
        "turboPressureSetpointBar" to "渦輪增壓目標值",
        "turboTempC" to "渦輪溫度",
        "mapPressureBar" to "進氣壓力（MAP）",
        "mapTempC" to "進氣溫度（MAP）",
        "oilPressureBar" to "機油壓力",
        "engineTorqueNm" to "引擎扭矩",
        "gearRaw" to "檔位",
        "tireFrontLeftPressureBar" to "左前胎壓",
        "tireFrontRightPressureBar" to "右前胎壓",
        "tireRearLeftPressureBar" to "左後胎壓",
        "tireRearRightPressureBar" to "右後胎壓",
        "tireFrontLeftTempC" to "左前胎溫",
        "tireFrontRightTempC" to "右前胎溫",
        "tireRearLeftTempC" to "左後胎溫",
        "tireRearRightTempC" to "右後胎溫",
        "auxBatteryVoltageV" to "輔助電瓶電壓",
        "auxBatteryTempC" to "輔助電瓶溫度",
        "fuelInstantConsumptionLh" to "即時油耗",
        "fuelTripConsumptionL" to "本趟油耗",
        "remainingRangeKmPSA" to "剩餘可行駛里程",
        // citroen-ev.json (Citroën/Peugeot EMP2 純電平台，取自 OVMS)
        "evBatteryVoltageV" to "高壓電池電壓",
        "evBatteryCurrentA" to "高壓電池電流",
        "evBatteryMinCellVoltageV" to "電池最低單體電壓",
        "evBatteryMaxCellVoltageV" to "電池最高單體電壓",
        "evBatteryAvailableKWh" to "可用電量",
        "evBatterySohPercent" to "電池健康度 (SOH)",
        "evAmbientTempC" to "外部氣溫（EV）",
        "evBatteryTempC" to "高壓電池溫度",
        "evDcDcConverterTempC" to "DC-DC 轉換器溫度",
        "evOnboardChargerTempC" to "車載充電器溫度",
        // mazda.json
        "tire1PressurePSI" to "胎壓 1",
        "tire2PressurePSI" to "胎壓 2",
        "tire3PressurePSI" to "胎壓 3",
        "tire4PressurePSI" to "胎壓 4",
        // ford.json
        "odometerKM" to "累積里程",
        "tirePressureWarning" to "胎壓警示燈",
        "tireFrontLeftPSI" to "左前胎壓",
        "tireFrontRightPSI" to "右前胎壓",
        "tireRearRightPSI" to "右後胎壓",
        "tireRearLeftPSI" to "左後胎壓",
        // honda.json
        "stateOfChargePercent" to "高壓電池電量",
        "batteryVoltage" to "高壓電池電壓",
        "batteryCurrent" to "高壓電池電流",
        "engineCoolantTemp1C" to "水溫 1",
        "engineCoolantTemp2C" to "水溫 2",
        "generatorDutyPercent" to "發電機占空比",
    )

    /** Traditional Chinese display name for [field], or the raw field key if untranslated. */
    fun displayName(field: String): String = zh[field] ?: field
}
